version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: orisai-dbaudit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  mariadb:
    image: mariadb:11.4
    container_name: orisai-dbaudit-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql-data:
  mariadb-data:
