<?php declare(strict_types = 1);

namespace Orisai\DbAudit\Ignore;

use Orisai\DbAudit\Report\ColumnViolationSource;
use Orisai\DbAudit\Report\TableViolationSource;
use Orisai\DbAudit\Report\Violation;
use Orisai\Exceptions\Logic\InvalidState;
use function array_values;
use function file_put_contents;
use function implode;
use function is_array;
use function is_int;
use function is_iterable;
use function is_string;
use function usort;
use function var_export;

/**
 * Reads and writes a baseline of ignored errors as a plain PHP file returning a list of entries. The file is meant
 * to be loaded explicitly from the runner wiring (it is never auto-discovered).
 */
final class Baseline
{

	public static function load(string $path): IgnoreList
	{
		$errors = [];
		foreach (self::readEntries($path) as $entry) {
			$errors[] = new IgnoredError(
				$entry['rawMessage'],
				null,
				$entry['table'],
				$entry['column'],
				$entry['key'],
				$entry['count'],
			);
		}

		return new IgnoreList($errors);
	}

	/**
	 * @param list<Violation> $violations
	 */
	public static function write(string $path, array $violations): void
	{
		$groups = [];
		foreach ($violations as $violation) {
			$table = self::sourceTable($violation);
			$column = self::sourceColumn($violation);
			$groupKey = implode("\0", [$violation->getKey(), $violation->getMessage(), $table ?? '', $column ?? '']);

			if (!isset($groups[$groupKey])) {
				$groups[$groupKey] = [
					'key' => $violation->getKey(),
					'rawMessage' => $violation->getMessage(),
					'table' => $table,
					'column' => $column,
					'count' => 0,
				];
			}

			$groups[$groupKey]['count']++;
		}

		$entries = array_values($groups);
		usort(
			$entries,
			static fn (array $a, array $b): int => [$a['key'], $a['rawMessage'], $a['table'] ?? '', $a['column'] ?? '']
				<=> [$b['key'], $b['rawMessage'], $b['table'] ?? '', $b['column'] ?? ''],
		);

		self::writeEntries($path, $entries);
	}

	public static function remove(string $path, BaselineFilter $filter): int
	{
		$kept = [];
		$removed = 0;
		foreach (self::readEntries($path) as $entry) {
			if ($filter->matches($entry)) {
				$removed++;
			} else {
				$kept[] = $entry;
			}
		}

		self::writeEntries($path, $kept);

		return $removed;
	}

	/**
	 * @return list<array{key: string|null, rawMessage: string|null, table: string|null, column: string|null, count: int|null}>
	 */
	private static function readEntries(string $path): array
	{
		$data = require $path;

		if (!is_iterable($data)) {
			throw InvalidState::create()
				->withMessage('Baseline file ' . $path . ' must return an iterable/array.');
		}

		$entries = [];
		foreach ($data as $row) {
			if (!is_array($row)) {
				throw InvalidState::create()
					->withMessage('Baseline file ' . $path . ' must contain only array entries.');
			}

			$entries[] = [
				'key' => self::optString($row, 'key'),
				'rawMessage' => self::optString($row, 'rawMessage'),
				'table' => self::optString($row, 'table'),
				'column' => self::optString($row, 'column'),
				'count' => self::optInt($row, 'count'),
			];
		}

		return $entries;
	}

	/**
	 * @param list<array{key: string|null, rawMessage: string|null, table: string|null, column: string|null, count: int|null}> $entries
	 */
	private static function writeEntries(string $path, array $entries): void
	{
		$lines = [
			'<?php declare(strict_types = 1);',
			'',
			'// Generated by db-audit. Load it explicitly from your runner wiring; it is not auto-discovered.',
			'',
			'return (static function (): iterable {',
		];

		if ($entries === []) {
			$lines[] = "\tyield from [];";
		} else {
			foreach ($entries as $i => $entry) {
				if ($i > 0) {
					$lines[] = '';
				}

				$lines[] = "\tyield [";
				foreach (['key', 'rawMessage', 'table', 'column'] as $field) {
					$value = $entry[$field];
					if ($value !== null) {
						$lines[] = "\t\t'" . $field . "' => " . var_export($value, true) . ',';
					}
				}

				if ($entry['count'] !== null) {
					$lines[] = "\t\t'count' => " . $entry['count'] . ',';
				}

				$lines[] = "\t];";
			}
		}

		$lines[] = '})();';

		file_put_contents($path, implode("\n", $lines) . "\n");
	}

	private static function sourceTable(Violation $violation): ?string
	{
		$source = $violation->getSource();

		if ($source instanceof ColumnViolationSource || $source instanceof TableViolationSource) {
			return $source->getTable();
		}

		return null;
	}

	private static function sourceColumn(Violation $violation): ?string
	{
		$source = $violation->getSource();

		return $source instanceof ColumnViolationSource ? $source->getColumn() : null;
	}

	/**
	 * @param array<mixed> $row
	 */
	private static function optString(array $row, string $key): ?string
	{
		$value = $row[$key] ?? null;

		if ($value !== null && !is_string($value)) {
			throw InvalidState::create()
				->withMessage('Baseline entry field ' . $key . ' must be a string or absent.');
		}

		return $value;
	}

	/**
	 * @param array<mixed> $row
	 */
	private static function optInt(array $row, string $key): ?int
	{
		$value = $row[$key] ?? null;

		if ($value !== null && !is_int($value)) {
			throw InvalidState::create()
				->withMessage('Baseline entry field ' . $key . ' must be an int or absent.');
		}

		return $value;
	}

}
